// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emfegtesqimsqyiagdtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZmVndGVzcWltc3F5aWFnZHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzQ4MjQsImV4cCI6MjA3MjI1MDgyNH0.CFVvrupCFg89o8MIV1JNeNrRhpfEzZbJiP2PUdNpV7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});